/**
 * CET-6 高频词汇数据（含真题语境）
 * 按词频排序，覆盖近5年真题高频词
 */
const { initDb, getDb, get, all, run } = require('./db');

const words = [
  // === 高频词 (频率 5+) ===
  { w: 'abandon', ph: '/əˈbændən/', pos: 'v.', cn: '放弃，遗弃', en: 'to give up completely', se: 'The government had to abandon the project due to lack of funding.', sc: '由于缺乏资金，政府不得不放弃该项目。', f: 5, d: 1 },
  { w: 'absorb', ph: '/əbˈzɔːb/', pos: 'v.', cn: '吸收，吸引', en: 'to take in or soak up', se: 'Plants absorb carbon dioxide from the atmosphere.', sc: '植物从大气中吸收二氧化碳。', f: 5, d: 1 },
  { w: 'abstract', ph: '/ˈæbstrækt/', pos: 'adj./n./v.', cn: '抽象的；摘要', en: 'existing in thought rather than matter', se: 'The concept of freedom is too abstract for young children to understand.', sc: '自由的概念对小孩子来说太抽象了，难以理解。', f: 5, d: 2 },
  { w: 'academic', ph: '/ˌækəˈdemɪk/', pos: 'adj.', cn: '学术的，学院的', en: 'relating to education and scholarship', se: 'She has a strong academic background in economics.', sc: '她在经济学方面有扎实的学术背景。', f: 6, d: 1 },
  { w: 'accelerate', ph: '/əkˈseləreɪt/', pos: 'v.', cn: '加速，促进', en: 'to increase speed', se: 'Climate change is accelerating at an alarming rate.', sc: '气候变化正在以惊人的速度加速。', f: 5, d: 2 },
  { w: 'accompany', ph: '/əˈkʌmpəni/', pos: 'v.', cn: '陪伴，伴随', en: 'to go somewhere with someone', se: 'Each recipe is accompanied by a photograph of the finished dish.', sc: '每份食谱都附有成品菜肴的照片。', f: 5, d: 2 },
  { w: 'accomplish', ph: '/əˈkʌmplɪʃ/', pos: 'v.', cn: '完成，实现', en: 'to achieve or complete successfully', se: 'We have accomplished all our goals for this quarter.', sc: '我们已经完成了本季度的所有目标。', f: 5, d: 2 },
  { w: 'accumulate', ph: '/əˈkjuːmjəleɪt/', pos: 'v.', cn: '积累，积聚', en: 'to gather or collect over time', se: 'Over the years, she accumulated a vast collection of rare books.', sc: '多年来，她积累了大量珍本收藏。', f: 5, d: 2 },
  { w: 'adapt', ph: '/əˈdæpt/', pos: 'v.', cn: '适应，改编', en: 'to adjust to new conditions', se: 'Companies must adapt to changing market conditions to survive.', sc: '公司必须适应不断变化的市场环境才能生存。', f: 6, d: 1 },
  { w: 'advocate', ph: '/ˈædvəkeɪt/', pos: 'v./n.', cn: '提倡，支持；提倡者', en: 'to publicly support a cause', se: 'Many environmentalists advocate for renewable energy sources.', sc: '许多环保人士提倡使用可再生能源。', f: 5, d: 2 },
  { w: 'affect', ph: '/əˈfekt/', pos: 'v.', cn: '影响，感动', en: 'to have an influence on', se: 'The new policy will affect millions of people across the country.', sc: '新政策将影响全国数百万人。', f: 6, d: 1 },
  { w: 'alternative', ph: '/ɔːlˈtɜːnətɪv/', pos: 'adj./n.', cn: '替代的；替代方案', en: 'one of two or more available possibilities', se: 'We need to find alternative sources of energy.', sc: '我们需要寻找替代能源。', f: 6, d: 1 },
  { w: 'analyze', ph: '/ˈænəlaɪz/', pos: 'v.', cn: '分析，解析', en: 'to examine in detail', se: 'Researchers analyzed the data from over 10,000 participants.', sc: '研究人员分析了来自一万多名参与者的数据。', f: 6, d: 1 },
  { w: 'annual', ph: '/ˈænjuəl/', pos: 'adj./n.', cn: '每年的；年度的', en: 'occurring once a year', se: 'The company publishes its annual report in March.', sc: '该公司在三月发布年度报告。', f: 5, d: 1 },
  { w: 'anticipate', ph: '/ænˈtɪsɪpeɪt/', pos: 'v.', cn: '预期，期望', en: 'to expect or predict', se: 'Sales are anticipated to rise by 15% this year.', sc: '今年的销售额预计将增长15%。', f: 5, d: 2 },
  { w: 'apparent', ph: '/əˈpærənt/', pos: 'adj.', cn: '明显的，表面上的', en: 'clearly visible or understood', se: 'It was apparent that she was not telling the truth.', sc: '很明显她没说实话。', f: 5, d: 1 },
  { w: 'approach', ph: '/əˈprəʊtʃ/', pos: 'v./n.', cn: '接近；方法，途径', en: 'a way of dealing with something', se: 'We need a new approach to solving this problem.', sc: '我们需要一种新的方法来解决这个问题。', f: 6, d: 1 },
  { w: 'appropriate', ph: '/əˈprəʊpriət/', pos: 'adj.', cn: '适当的，恰当的', en: 'suitable or proper', se: 'It is not appropriate to wear casual clothes to a formal interview.', sc: '穿休闲装参加正式面试是不合适的。', f: 5, d: 1 },
  { w: 'assess', ph: '/əˈses/', pos: 'v.', cn: '评估，评定', en: 'to evaluate or estimate', se: 'It is difficult to assess the long-term effects of the policy.', sc: '很难评估这项政策的长期影响。', f: 5, d: 1 },
  { w: 'assume', ph: '/əˈsjuːm/', pos: 'v.', cn: '假设，承担', en: 'to suppose without proof', se: 'We cannot simply assume that the economy will recover quickly.', sc: '我们不能简单地假设经济会迅速复苏。', f: 5, d: 1 },
  { w: 'atmosphere', ph: '/ˈætməsfɪə/', pos: 'n.', cn: '大气，氛围', en: 'the gases surrounding the earth; mood', se: 'The restaurant has a warm and inviting atmosphere.', sc: '这家餐厅氛围温馨宜人。', f: 5, d: 1 },
  { w: 'available', ph: '/əˈveɪləbl/', pos: 'adj.', cn: '可用的，有效的', en: 'able to be used or obtained', se: 'Tickets are available online starting next Monday.', sc: '门票从下周一起可在网上购买。', f: 6, d: 1 },
  { w: 'barrier', ph: '/ˈbæriə/', pos: 'n.', cn: '障碍，屏障', en: 'something that blocks progress', se: 'Language barriers often prevent immigrants from accessing healthcare.', sc: '语言障碍常常阻碍移民获得医疗服务。', f: 5, d: 1 },
  { w: 'benefit', ph: '/ˈbenɪfɪt/', pos: 'n./v.', cn: '利益，好处；受益', en: 'an advantage or profit', se: 'Regular exercise has many health benefits.', sc: '经常锻炼对健康有很多好处。', f: 6, d: 1 },
  { w: 'budget', ph: '/ˈbʌdʒɪt/', pos: 'n./v.', cn: '预算', en: 'an estimate of income and expenditure', se: 'The project was completed under budget and ahead of schedule.', sc: '该项目在预算内提前完成了。', f: 5, d: 1 },
  { w: 'capacity', ph: '/kəˈpæsəti/', pos: 'n.', cn: '能力，容量', en: 'the ability to hold or produce', se: 'The stadium has a seating capacity of 50,000.', sc: '该体育场可容纳五万人。', f: 5, d: 2 },
  { w: 'category', ph: '/ˈkætəɡəri/', pos: 'n.', cn: '类别，种类', en: 'a class or division', se: 'The entries are divided into three categories.', sc: '参赛作品分为三类。', f: 5, d: 1 },
  { w: 'challenge', ph: '/ˈtʃælɪndʒ/', pos: 'n./v.', cn: '挑战', en: 'a difficult task or problem', se: 'Finding affordable housing is a major challenge for young people.', sc: '找到负担得起的住房是年轻人面临的主要挑战。', f: 6, d: 1 },
  { w: 'characteristic', ph: '/ˌkærəktəˈrɪstɪk/', pos: 'adj./n.', cn: '典型的；特征', en: 'a distinguishing quality', se: 'Warmth is a characteristic of Mediterranean hospitality.', sc: '热情是地中海式好客的特点。', f: 5, d: 2 },
  { w: 'circumstance', ph: '/ˈsɜːkəmstəns/', pos: 'n.', cn: '环境，情况', en: 'the conditions affecting a situation', se: 'Under no circumstances should you open the door to strangers.', sc: '在任何情况下都不应该给陌生人开门。', f: 5, d: 2 },
  { w: 'collapse', ph: '/kəˈlæps/', pos: 'v./n.', cn: '倒塌，崩溃', en: 'to fall down or fail suddenly', se: 'The stock market collapsed, causing a global financial crisis.', sc: '股市崩盘，引发了全球金融危机。', f: 5, d: 2 },
  { w: 'commission', ph: '/kəˈmɪʃn/', pos: 'n./v.', cn: '委员会；委托', en: 'a group appointed to perform a function', se: 'The European Commission has proposed new environmental regulations.', sc: '欧盟委员会提出了新的环保法规。', f: 5, d: 2 },
  { w: 'commitment', ph: '/kəˈmɪtmənt/', pos: 'n.', cn: '承诺，投入', en: 'a pledge or dedication', se: 'The company has a strong commitment to environmental sustainability.', sc: '该公司对环境可持续发展有着坚定的承诺。', f: 5, d: 2 },
  { w: 'compensate', ph: '/ˈkɒmpenseɪt/', pos: 'v.', cn: '补偿，弥补', en: 'to make up for loss or damage', se: 'The insurance company will compensate you for the damage to your car.', sc: '保险公司将赔偿你汽车的损坏。', f: 5, d: 3 },
  { w: 'component', ph: '/kəmˈpəʊnənt/', pos: 'n.', cn: '成分，组件', en: 'a part of a larger whole', se: 'Each component of the engine must be carefully tested.', sc: '发动机的每个部件都必须仔细测试。', f: 5, d: 2 },
  { w: 'concentrate', ph: '/ˈkɒnsəntreɪt/', pos: 'v.', cn: '集中，专注', en: 'to focus attention', se: 'I find it hard to concentrate in a noisy environment.', sc: '我发现在嘈杂的环境中很难集中注意力。', f: 5, d: 1 },
  { w: 'concept', ph: '/ˈkɒnsept/', pos: 'n.', cn: '概念，观念', en: 'an abstract idea', se: 'The concept of sustainable development gained global recognition.', sc: '可持续发展的概念得到了全球认可。', f: 6, d: 1 },
  { w: 'consequence', ph: '/ˈkɒnsɪkwəns/', pos: 'n.', cn: '结果，后果', en: 'a result or effect', se: 'Global warming has serious consequences for the planet.', sc: '全球变暖对地球有严重的后果。', f: 6, d: 1 },
  { w: 'conservation', ph: '/ˌkɒnsəˈveɪʃn/', pos: 'n.', cn: '保护，保存', en: 'the protection of natural resources', se: 'Wildlife conservation efforts have helped protect endangered species.', sc: '野生动物保护工作帮助保护了濒危物种。', f: 5, d: 2 },
  { w: 'considerable', ph: '/kənˈsɪdərəbl/', pos: 'adj.', cn: '相当大的，重要的', en: 'large in amount or extent', se: 'The project required a considerable amount of time and effort.', sc: '该项目需要大量的时间和精力。', f: 5, d: 2 },
  { w: 'consistent', ph: '/kənˈsɪstənt/', pos: 'adj.', cn: '一致的，一贯的', en: 'unchanging in nature or effect', se: 'We need a consistent approach to quality control.', sc: '我们需要一致的质控方法。', f: 5, d: 2 },
  { w: 'contemporary', ph: '/kənˈtempərəri/', pos: 'adj.', cn: '当代的，同时代的', en: 'living or occurring at the same time', se: 'The museum showcases both classical and contemporary art.', sc: '该博物馆展出古典和当代艺术作品。', f: 5, d: 2 },
  { w: 'contribute', ph: '/kənˈtrɪbjuːt/', pos: 'v.', cn: '贡献，捐献', en: 'to give or supply in common with others', se: 'Everyone should contribute to protecting the environment.', sc: '每个人都应该为保护环境做出贡献。', f: 6, d: 1 },
  { w: 'controversy', ph: '/ˈkɒntrəvɜːsi/', pos: 'n.', cn: '争议，争论', en: 'a prolonged public dispute', se: 'The new policy has sparked considerable controversy.', sc: '这项新政策引发了相当大的争议。', f: 5, d: 3 },
  { w: 'conventional', ph: '/kənˈvenʃənl/', pos: 'adj.', cn: '传统的，惯例的', en: 'based on what is traditionally done', se: 'Conventional farming methods rely heavily on chemical fertilizers.', sc: '传统耕作方法严重依赖化肥。', f: 5, d: 2 },
  { w: 'convince', ph: '/kənˈvɪns/', pos: 'v.', cn: '使确信，说服', en: 'to cause someone to believe', se: 'The evidence convinced the jury of his innocence.', sc: '证据使陪审团相信他是无辜的。', f: 5, d: 1 },
  { w: 'critical', ph: '/ˈkrɪtɪkl/', pos: 'adj.', cn: '批评的，关键的', en: 'expressing disapproval; crucial', se: 'It is critical that we address climate change immediately.', sc: '我们立即应对气候变化至关重要。', f: 5, d: 1 },
  { w: 'crucial', ph: '/ˈkruːʃl/', pos: 'adj.', cn: '至关重要的', en: 'extremely important', se: 'Early detection is crucial for successful cancer treatment.', sc: '早期发现对癌症成功治疗至关重要。', f: 5, d: 1 },
  { w: 'decline', ph: '/dɪˈklaɪn/', pos: 'v./n.', cn: '下降，衰退', en: 'to become smaller or weaker', se: 'The number of wild tigers has declined sharply over the past century.', sc: '过去一个世纪里野生老虎的数量急剧下降。', f: 6, d: 1 },
  { w: 'demonstrate', ph: '/ˈdemənstreɪt/', pos: 'v.', cn: '证明，演示', en: 'to show clearly', se: 'The study demonstrates the link between diet and heart disease.', sc: '这项研究证明了饮食与心脏病之间的联系。', f: 5, d: 1 },
  { w: 'depress', ph: '/dɪˈpres/', pos: 'v.', cn: '使沮丧，压抑', en: 'to make someone feel sad', se: 'The gloomy weather tends to depress most people.', sc: '阴沉的天气往往使大多数人感到压抑。', f: 5, d: 2 },
  { w: 'deserve', ph: '/dɪˈzɜːv/', pos: 'v.', cn: '值得，应得', en: 'to be worthy of', se: 'Everyone deserves a fair chance to succeed.', sc: '每个人都值得拥有公平的成功机会。', f: 5, d: 1 },
  { w: 'determine', ph: '/dɪˈtɜːmɪn/', pos: 'v.', cn: '决定，确定', en: 'to decide or settle', se: 'Your attitude determines your success in life.', sc: '你的态度决定了你人生的成功。', f: 5, d: 1 },
  { w: 'device', ph: '/dɪˈvaɪs/', pos: 'n.', cn: '装置，设备', en: 'a tool or piece of equipment', se: 'Electronic devices have become an essential part of our daily lives.', sc: '电子设备已成为我们日常生活中必不可少的一部分。', f: 5, d: 1 },
  { w: 'discipline', ph: '/ˈdɪsəplɪn/', pos: 'n./v.', cn: '纪律；训练', en: 'the practice of training people to obey rules', se: 'Learning a musical instrument requires patience and discipline.', sc: '学习乐器需要耐心和纪律。', f: 5, d: 2 },
  { w: 'distinguish', ph: '/dɪˈstɪŋɡwɪʃ/', pos: 'v.', cn: '区分，辨别', en: 'to recognize differences', se: 'It is often difficult to distinguish between genuine and fake products.', sc: '区分真伪产品往往很困难。', f: 5, d: 2 },
  { w: 'diverse', ph: '/daɪˈvɜːs/', pos: 'adj.', cn: '多样的，不同的', en: 'showing a great deal of variety', se: 'New York is one of the most culturally diverse cities in the world.', sc: '纽约是世界上文化最多元的城市之一。', f: 5, d: 1 },
  { w: 'domestic', ph: '/dəˈmestɪk/', pos: 'adj.', cn: '国内的，家庭的', en: 'relating to a home or home country', se: 'The government aims to boost domestic consumption.', sc: '政府旨在提振国内消费。', f: 5, d: 1 },
  { w: 'dominate', ph: '/ˈdɒmɪneɪt/', pos: 'v.', cn: '支配，主导', en: 'to have power and control over', se: 'The tech giant dominates the global smartphone market.', sc: '这家科技巨头主导着全球智能手机市场。', f: 5, d: 2 },
  { w: 'dramatic', ph: '/drəˈmætɪk/', pos: 'adj.', cn: '戏剧性的，巨大的', en: 'striking or sudden', se: 'The Internet has brought about dramatic changes in communication.', sc: '互联网给通信带来了巨大的变化。', f: 5, d: 1 },
  { w: 'duration', ph: '/djuˈreɪʃn/', pos: 'n.', cn: '持续时间', en: 'the length of time something lasts', se: 'The duration of the course is three months.', sc: '该课程的持续时间为三个月。', f: 5, d: 1 },
  { w: 'dynamic', ph: '/daɪˈnæmɪk/', pos: 'adj./n.', cn: '动态的；动力', en: 'characterized by constant change or activity', se: 'The job market is dynamic and constantly evolving.', sc: '就业市场是动态的，不断在演变。', f: 5, d: 2 },
  { w: 'eliminate', ph: '/ɪˈlɪmɪneɪt/', pos: 'v.', cn: '消除，淘汰', en: 'to completely remove', se: 'The goal is to eliminate poverty by 2030.', sc: '目标是在2030年前消除贫困。', f: 5, d: 2 },
  { w: 'emerge', ph: '/ɪˈmɜːdʒ/', pos: 'v.', cn: '出现，浮现', en: 'to come out into view', se: 'New challenges emerge as technology advances.', sc: '随着技术的进步，新的挑战不断出现。', f: 5, d: 1 },
  { w: 'emphasis', ph: '/ˈemfəsɪs/', pos: 'n.', cn: '强调，重点', en: 'special importance or stress', se: 'The school places great emphasis on moral education.', sc: '学校非常重视道德教育。', f: 5, d: 2 },
  { w: 'enable', ph: '/ɪˈneɪbl/', pos: 'v.', cn: '使能够', en: 'to make possible or feasible', se: 'The scholarship enabled him to attend university.', sc: '奖学金使他能够上大学。', f: 6, d: 1 },
  { w: 'encounter', ph: '/ɪnˈkaʊntə/', pos: 'v./n.', cn: '遭遇，邂逅', en: 'to meet unexpectedly', se: 'She encountered many difficulties during her research.', sc: '她在研究过程中遇到了许多困难。', f: 5, d: 2 },
  { w: 'enormous', ph: '/ɪˈnɔːməs/', pos: 'adj.', cn: '巨大的，庞大的', en: 'very large in size or amount', se: 'The project requires an enormous amount of investment.', sc: '该项目需要巨额投资。', f: 5, d: 1 },
  { w: 'establish', ph: '/ɪˈstæblɪʃ/', pos: 'v.', cn: '建立，确立', en: 'to set up or create', se: 'The company was established in 1995.', sc: '该公司成立于1995年。', f: 6, d: 1 },
  { w: 'evaluate', ph: '/ɪˈvæljueɪt/', pos: 'v.', cn: '评价，评估', en: 'to assess or appraise', se: 'It is too early to evaluate the effectiveness of the new policy.', sc: '评估新政策的有效性还为时过早。', f: 5, d: 1 },
  { w: 'evidence', ph: '/ˈevɪdəns/', pos: 'n.', cn: '证据，迹象', en: 'facts or signs showing something is true', se: 'There is growing evidence that exercise improves mental health.', sc: '越来越多的证据表明锻炼能改善心理健康。', f: 6, d: 1 },
  { w: 'evolve', ph: '/ɪˈvɒlv/', pos: 'v.', cn: '进化，演变', en: 'to develop gradually', se: 'The company has evolved from a small startup into a global corporation.', sc: '该公司已从一个小型初创企业发展成为一家全球性公司。', f: 5, d: 2 },

  // === 中高频词 (频率 3-4) ===
  { w: 'exceed', ph: '/ɪkˈsiːd/', pos: 'v.', cn: '超过，超越', en: 'to go beyond a limit', se: 'The demand for the product has exceeded all expectations.', sc: '对该产品的需求超出了所有预期。', f: 4, d: 2 },
  { w: 'exhibit', ph: '/ɪɡˈzɪbɪt/', pos: 'v./n.', cn: '展览，展示；展品', en: 'to display or show', se: 'The museum is exhibiting a collection of ancient artifacts.', sc: '博物馆正在展出一批古代文物。', f: 4, d: 2 },
  { w: 'expand', ph: '/ɪkˈspænd/', pos: 'v.', cn: '扩大，膨胀', en: 'to become larger', se: 'The company plans to expand its operations overseas.', sc: '该公司计划将业务扩展到海外。', f: 5, d: 1 },
  { w: 'expose', ph: '/ɪkˈspəʊz/', pos: 'v.', cn: '暴露，揭露', en: 'to reveal or make visible', se: 'The documentary exposed the harsh reality of child labor.', sc: '这部纪录片揭露了童工劳动的残酷现实。', f: 5, d: 2 },
  { w: 'extend', ph: '/ɪkˈstend/', pos: 'v.', cn: '延伸，延长', en: 'to stretch out or prolong', se: 'The government decided to extend the deadline for tax payments.', sc: '政府决定延长纳税截止日期。', f: 5, d: 1 },
  { w: 'extensive', ph: '/ɪkˈstensɪv/', pos: 'adj.', cn: '广泛的，大量的', en: 'covering a large area or amount', se: 'The storm caused extensive damage to coastal communities.', sc: '风暴对沿海社区造成了广泛的破坏。', f: 5, d: 1 },
  { w: 'external', ph: '/ɪkˈstɜːnl/', pos: 'adj.', cn: '外部的，外面的', en: 'situated outside', se: 'The company hired an external consultant to review its operations.', sc: '公司聘请了一位外部顾问来审查其运营。', f: 4, d: 2 },
  { w: 'feasible', ph: '/ˈfiːzəbl/', pos: 'adj.', cn: '可行的', en: 'possible to achieve', se: 'Engineers concluded that the bridge project was economically feasible.', sc: '工程师们得出结论，这座桥的项目在经济上是可行的。', f: 4, d: 2 },
  { w: 'fluctuate', ph: '/ˈflʌktʃueɪt/', pos: 'v.', cn: '波动，起伏', en: 'to change irregularly', se: 'Oil prices fluctuate according to global demand.', sc: '石油价格根据全球需求波动。', f: 4, d: 3 },
  { w: 'forecast', ph: '/ˈfɔːkɑːst/', pos: 'v./n.', cn: '预测，预报', en: 'to predict future events', se: 'The weather forecast predicts rain for the weekend.', sc: '天气预报预测周末有雨。', f: 4, d: 1 },
  { w: 'fundamental', ph: '/ˌfʌndəˈmentl/', pos: 'adj.', cn: '基本的，根本的', en: 'forming a necessary base', se: 'There is a fundamental difference between the two political systems.', sc: '这两种政治体制存在根本性的差异。', f: 5, d: 2 },
  { w: 'generate', ph: '/ˈdʒenəreɪt/', pos: 'v.', cn: '产生，生成', en: 'to produce or create', se: 'The wind turbines generate enough electricity to power 500 homes.', sc: '这些风力发电机产生的电力足以供应500户家庭。', f: 5, d: 1 },
  { w: 'genuine', ph: '/ˈdʒenjuɪn/', pos: 'adj.', cn: '真正的，真诚的', en: 'truly what it is said to be', se: 'She showed genuine concern for the welfare of her students.', sc: '她对自己的学生表现出真切的关心。', f: 4, d: 2 },
  { w: 'global', ph: '/ˈɡləʊbl/', pos: 'adj.', cn: '全球的，全面的', en: 'relating to the whole world', se: 'Globalization has had a profound impact on world economies.', sc: '全球化对世界经济产生了深远的影响。', f: 6, d: 1 },
  { w: 'guarantee', ph: '/ˌɡærənˈtiː/', pos: 'v./n.', cn: '保证，担保', en: 'a formal assurance', se: 'The product comes with a two-year guarantee.', sc: '该产品享有两年保修。', f: 5, d: 1 },
  { w: 'hesitate', ph: '/ˈhezɪteɪt/', pos: 'v.', cn: '犹豫，迟疑', en: 'to pause before acting', se: 'If you have any questions, please do not hesitate to ask.', sc: '如果有任何问题，请尽管提问。', f: 4, d: 1 },
  { w: 'identical', ph: '/aɪˈdentɪkl/', pos: 'adj.', cn: '相同的，一致的', en: 'exactly the same', se: 'The two test results were almost identical.', sc: '两次测试结果几乎完全相同。', f: 4, d: 2 },
  { w: 'ignorant', ph: '/ˈɪɡnərənt/', pos: 'adj.', cn: '无知的，不了解的', en: 'lacking knowledge or awareness', se: 'Many people are ignorant of the dangers of excessive sugar consumption.', sc: '许多人不知道过量摄入糖的危害。', f: 4, d: 2 },
  { w: 'illustrate', ph: '/ˈɪləstreɪt/', pos: 'v.', cn: '说明，插图说明', en: 'to explain or make clear', se: 'The graph illustrates the relationship between income and education.', sc: '该图表说明了收入与教育之间的关系。', f: 4, d: 2 },
  { w: 'immense', ph: '/ɪˈmens/', pos: 'adj.', cn: '巨大的，无边的', en: 'extremely large or great', se: 'The Internet has had an immense impact on how we communicate.', sc: '互联网对我们交流方式产生了巨大的影响。', f: 4, d: 1 },
  { w: 'implement', ph: '/ˈɪmplɪment/', pos: 'v.', cn: '实施，执行', en: 'to put into effect', se: 'The government will implement the new policy next month.', sc: '政府将于下月实施新政策。', f: 5, d: 2 },
  { w: 'implication', ph: '/ˌɪmplɪˈkeɪʃn/', pos: 'n.', cn: '含义，暗示', en: 'a possible consequence or effect', se: 'The research findings have significant implications for public health.', sc: '这些研究结果对公共健康有重要的启示。', f: 5, d: 2 },
  { w: 'impose', ph: '/ɪmˈpəʊz/', pos: 'v.', cn: '强加，征收', en: 'to force something on someone', se: 'The government plans to impose a carbon tax on large polluters.', sc: '政府计划对大污染企业征收碳税。', f: 5, d: 2 },
  { w: 'incredible', ph: '/ɪnˈkredəbl/', pos: 'adj.', cn: '难以置信的', en: 'impossible or hard to believe', se: 'It is incredible how much technology has advanced in the past decade.', sc: '过去十年技术进步之大令人难以置信。', f: 4, d: 1 },
  { w: 'independent', ph: '/ˌɪndɪˈpendənt/', pos: 'adj.', cn: '独立的，自主的', en: 'free from outside control', se: 'The country became independent in 1965.', sc: '该国于1965年独立。', f: 5, d: 1 },
  { w: 'indicate', ph: '/ˈɪndɪkeɪt/', pos: 'v.', cn: '表明，指示', en: 'to point out or show', se: 'The survey indicates a growing concern about climate change.', sc: '调查显示人们对气候变化的担忧日益增加。', f: 5, d: 1 },
  { w: 'inevitable', ph: '/ɪnˈevɪtəbl/', pos: 'adj.', cn: '不可避免的', en: 'certain to happen', se: 'Change is inevitable in any growing organization.', sc: '在任何成长中的组织里，变化是不可避免的。', f: 5, d: 2 },
  { w: 'influence', ph: '/ˈɪnfluəns/', pos: 'n./v.', cn: '影响，影响力', en: 'the power to affect something', se: 'The media plays a powerful influence on public opinion.', sc: '媒体对公众舆论有强大的影响力。', f: 6, d: 1 },
  { w: 'initiative', ph: '/ɪˈnɪʃətɪv/', pos: 'n.', cn: '倡议，主动性', en: 'a new plan or action to solve a problem', se: 'The government launched a new initiative to promote renewable energy.', sc: '政府发起了一项推广可再生能源的新倡议。', f: 5, d: 2 },
  { w: 'innovation', ph: '/ˌɪnəˈveɪʃn/', pos: 'n.', cn: '创新，革新', en: 'a new method or idea', se: 'Technological innovation is the key to economic growth.', sc: '技术创新是经济增长的关键。', f: 5, d: 2 },
  { w: 'inspect', ph: '/ɪnˈspekt/', pos: 'v.', cn: '检查，检阅', en: 'to examine closely', se: 'Health inspectors regularly visit restaurants to ensure food safety.', sc: '卫生检查员定期检查餐厅以确保食品安全。', f: 4, d: 2 },
  { w: 'inspire', ph: '/ɪnˈspaɪə/', pos: 'v.', cn: '激励，启发', en: 'to motivate or encourage', se: 'Her speech inspired many young people to pursue their dreams.', sc: '她的演讲激励了许多年轻人追求梦想。', f: 5, d: 1 },
  { w: 'institution', ph: '/ˌɪnstɪˈtjuːʃn/', pos: 'n.', cn: '机构，制度', en: 'an established organization or custom', se: 'The university is one of the oldest educational institutions in the country.', sc: '这所大学是该国最古老的教育机构之一。', f: 5, d: 2 },
  { w: 'integrate', ph: '/ˈɪntɪɡreɪt/', pos: 'v.', cn: '整合，使完整', en: 'to combine into a whole', se: 'The new system integrates all our customer data into one platform.', sc: '新系统将我们所有的客户数据整合到一个平台上。', f: 5, d: 2 },
  { w: 'intellectual', ph: '/ˌɪntəˈlektʃuəl/', pos: 'adj./n.', cn: '智力的；知识分子', en: 'relating to the intellect', se: 'Reading is an excellent intellectual exercise.', sc: '阅读是一种极好的智力锻炼。', f: 4, d: 2 },
  { w: 'intense', ph: '/ɪnˈtens/', pos: 'adj.', cn: '强烈的，紧张的', en: 'very strong or extreme', se: 'The intense heat made it difficult to work outdoors.', sc: '酷热使得户外工作变得困难。', f: 4, d: 1 },
  { w: 'interfere', ph: '/ˌɪntəˈfɪə/', pos: 'v.', cn: '干涉，干扰', en: 'to get involved in something without invitation', se: 'The government should not interfere with the free market.', sc: '政府不应干涉自由市场。', f: 4, d: 2 },
  { w: 'interpret', ph: '/ɪnˈtɜːprɪt/', pos: 'v.', cn: '解释，口译', en: 'to explain or translate', se: 'It is difficult to interpret the results of the study without context.', sc: '没有背景信息很难解释这项研究的结果。', f: 4, d: 2 },
  { w: 'investigate', ph: '/ɪnˈvestɪɡeɪt/', pos: 'v.', cn: '调查，研究', en: 'to examine systematically', se: 'Police are investigating the cause of the accident.', sc: '警方正在调查事故原因。', f: 4, d: 1 },
  { w: 'investment', ph: '/ɪnˈvestmənt/', pos: 'n.', cn: '投资', en: 'the act of investing money', se: 'Education is the best investment for the future.', sc: '教育是对未来最好的投资。', f: 5, d: 1 },
  { w: 'isolate', ph: '/ˈaɪsəleɪt/', pos: 'v.', cn: '隔离，孤立', en: 'to separate from others', se: 'Patients with the infectious disease were isolated from the rest.', sc: '患有传染病的患者被隔离起来。', f: 4, d: 2 },
  { w: 'journal', ph: '/ˈdʒɜːnl/', pos: 'n.', cn: '期刊，日记', en: 'a newspaper or diary', se: 'She keeps a daily journal of her thoughts and experiences.', sc: '她每天记录自己的思考和经历。', f: 4, d: 1 },
  { w: 'justify', ph: '/ˈdʒʌstɪfaɪ/', pos: 'v.', cn: '证明正当，辩护', en: 'to show to be right or reasonable', se: 'The end does not justify the means.', sc: '目的并不能证明手段的正当性。', f: 4, d: 2 },
  { w: 'launch', ph: '/lɔːntʃ/', pos: 'v./n.', cn: '发射，启动', en: 'to send or start something', se: 'The company plans to launch a new product next spring.', sc: '该公司计划明年春天推出一款新产品。', f: 5, d: 1 },
  { w: 'legislation', ph: '/ˌledʒɪsˈleɪʃn/', pos: 'n.', cn: '立法，法规', en: 'a law or set of laws', se: 'New legislation requires all cars to meet stricter emission standards.', sc: '新立法要求所有汽车符合更严格的排放标准。', f: 5, d: 3 },
  { w: 'maintain', ph: '/meɪnˈteɪn/', pos: 'v.', cn: '维持，保养', en: 'to keep in good condition', se: 'It is important to maintain a healthy diet and exercise regularly.', sc: '保持健康饮食和定期锻炼很重要。', f: 6, d: 1 },
  { w: 'massive', ph: '/ˈmæsɪv/', pos: 'adj.', cn: '大规模的，大量的', en: 'large in size or amount', se: 'The company made a massive investment in renewable energy.', sc: '该公司对可再生能源进行了大规模投资。', f: 5, d: 1 },
  { w: 'mechanism', ph: '/ˈmekənɪzəm/', pos: 'n.', cn: '机制，机理', en: 'a system of parts working together', se: 'The market mechanism helps allocate resources efficiently.', sc: '市场机制有助于有效配置资源。', f: 5, d: 3 },
  { w: 'minimum', ph: '/ˈmɪnɪməm/', pos: 'adj./n.', cn: '最小的；最小值', en: 'the least possible amount', se: 'A minimum of two years of experience is required for this job.', sc: '这份工作至少需要两年经验。', f: 4, d: 1 },
  { w: 'modify', ph: '/ˈmɒdɪfaɪ/', pos: 'v.', cn: '修改，调整', en: 'to make partial changes', se: 'The design was modified to meet safety requirements.', sc: '设计被修改以符合安全要求。', f: 4, d: 1 },
  { w: 'monitor', ph: '/ˈmɒnɪtə/', pos: 'v./n.', cn: '监控；监视器', en: 'to observe and check over time', se: 'Doctors monitored the patient\'s condition throughout the night.', sc: '医生整夜监测病人的状况。', f: 5, d: 1 },
  { w: 'moral', ph: '/ˈmɒrəl/', pos: 'adj./n.', cn: '道德的；寓意', en: 'concerned with right and wrong', se: 'The film has a clear moral message about the dangers of greed.', sc: '这部电影传达了关于贪婪危害的明确道德信息。', f: 4, d: 1 },
  { w: 'negotiate', ph: '/nɪˈɡəʊʃieɪt/', pos: 'v.', cn: '谈判，协商', en: 'to discuss to reach an agreement', se: 'Union leaders are negotiating with management for better working conditions.', sc: '工会领导正在与管理层谈判，争取更好的工作条件。', f: 4, d: 2 },
  { w: 'network', ph: '/ˈnetwɜːk/', pos: 'n./v.', cn: '网络；建立联系', en: 'a group of interconnected things', se: 'Building a strong professional network is essential for career growth.', sc: '建立强大的专业网络对职业发展至关重要。', f: 5, d: 1 },
  { w: 'nevertheless', ph: '/ˌnevəðəˈles/', pos: 'adv.', cn: '然而，不过', en: 'in spite of that', se: 'The task was difficult; nevertheless, she completed it on time.', sc: '任务很艰巨，但她还是按时完成了。', f: 4, d: 2 },
  { w: 'norm', ph: '/nɔːm/', pos: 'n.', cn: '规范，标准', en: 'a standard or pattern', se: 'Working from home has become the new norm for many white-collar workers.', sc: '在家办公已成为许多白领的新常态。', f: 4, d: 2 },
  { w: 'obtain', ph: '/əbˈteɪn/', pos: 'v.', cn: '获得，获取', en: 'to get or acquire', se: 'It is becoming harder to obtain a mortgage for first-time buyers.', sc: '首次购房者越来越难获得抵押贷款。', f: 5, d: 1 },
  { w: 'obvious', ph: '/ˈɒbviəs/', pos: 'adj.', cn: '明显的，显然的', en: 'easily seen or understood', se: 'It was obvious that she had been crying.', sc: '很明显她哭过。', f: 4, d: 1 },
  { w: 'occupy', ph: '/ˈɒkjupaɪ/', pos: 'v.', cn: '占据，使忙碌', en: 'to fill space or time', se: 'The issue continues to occupy a central place in public debate.', sc: '这个问题继续在公众辩论中占据核心位置。', f: 4, d: 2 },
  { w: 'option', ph: '/ˈɒpʃn/', pos: 'n.', cn: '选择，选项', en: 'a thing that can be chosen', se: 'Students have the option to study abroad in their third year.', sc: '学生在第三年可以选择出国留学。', f: 5, d: 1 },
  { w: 'organize', ph: '/ˈɔːɡənaɪz/', pos: 'v.', cn: '组织，安排', en: 'to arrange in a structured way', se: 'The conference was organized by a team of volunteers.', sc: '这次会议由一群志愿者组织。', f: 5, d: 1 },
  { w: 'origin', ph: '/ˈɒrɪdʒɪn/', pos: 'n.', cn: '起源，来源', en: 'the point where something begins', se: 'The origin of the species remains a fascinating scientific question.', sc: '物种起源仍然是一个引人入胜的科学问题。', f: 4, d: 1 },
  { w: 'outcome', ph: '/ˈaʊtkʌm/', pos: 'n.', cn: '结果，成果', en: 'the final result', se: 'The outcome of the election surprised many political analysts.', sc: '选举的结果让许多政治分析家感到意外。', f: 5, d: 1 },
  { w: 'panic', ph: '/ˈpænɪk/', pos: 'n./v.', cn: '恐慌，惊慌', en: 'sudden uncontrollable fear', se: 'There is no need to panic — the situation is under control.', sc: '没有必要恐慌——局势在控制之中。', f: 3, d: 1 },
  { w: 'participate', ph: '/pɑːˈtɪsɪpeɪt/', pos: 'v.', cn: '参与，参加', en: 'to take part in', se: 'Employees are encouraged to participate in the company\'s wellness program.', sc: '鼓励员工参加公司的健康计划。', f: 5, d: 1 },
  { w: 'phenomenon', ph: '/fɪˈnɒmɪnən/', pos: 'n.', cn: '现象', en: 'a fact or event that can be observed', se: 'Globalization is a complex phenomenon with both positive and negative aspects.', sc: '全球化是一个复杂的现象，既有积极的一面也有消极的一面。', f: 5, d: 2 },
  { w: 'philosophy', ph: '/fɪˈlɒsəfi/', pos: 'n.', cn: '哲学，理念', en: 'the study of fundamental questions', se: 'The company\'s business philosophy emphasizes customer satisfaction above all.', sc: '公司的经营理念将客户满意度放在首位。', f: 4, d: 2 },
  { w: 'portion', ph: '/ˈpɔːʃn/', pos: 'n.', cn: '部分，一份', en: 'a part of a whole', se: 'A large portion of the budget is spent on education.', sc: '预算的很大一部分用于教育。', f: 4, d: 1 },
  { w: 'potential', ph: '/pəˈtenʃl/', pos: 'adj./n.', cn: '潜在的；潜力', en: 'having the capacity to develop', se: 'The region has great potential for economic development.', sc: '该地区具有巨大的经济发展潜力。', f: 6, d: 1 },
  { w: 'previous', ph: '/ˈpriːviəs/', pos: 'adj.', cn: '先前的，以前的', en: 'existing before in time', se: 'The previous record was broken by a wide margin.', sc: '之前的纪录被大幅打破。', f: 5, d: 1 },
  { w: 'principle', ph: '/ˈprɪnsəpl/', pos: 'n.', cn: '原则，原理', en: 'a fundamental rule or belief', se: 'We must uphold the principle of equality before the law.', sc: '我们必须维护法律面前人人平等的原则。', f: 5, d: 2 },
  { w: 'professional', ph: '/prəˈfeʃənl/', pos: 'adj./n.', cn: '专业的；专业人士', en: 'relating to a skilled job', se: 'She maintains a high level of professional ethics.', sc: '她保持着高水平的职业道德。', f: 5, d: 1 },
  { w: 'profound', ph: '/prəˈfaʊnd/', pos: 'adj.', cn: '深刻的，深远的', en: 'very great or intense', se: 'The discovery had a profound impact on medical science.', sc: '这一发现对医学科学产生了深远的影响。', f: 4, d: 2 },
  { w: 'prohibit', ph: '/prəˈhɪbɪt/', pos: 'v.', cn: '禁止，阻止', en: 'to forbid by law', se: 'Smoking is prohibited in all public buildings.', sc: '所有公共建筑内禁止吸烟。', f: 4, d: 2 },
  { w: 'promote', ph: '/prəˈməʊt/', pos: 'v.', cn: '促进，推广，升职', en: 'to encourage or support', se: 'The campaign promotes healthy eating habits among teenagers.', sc: '这项运动倡导青少年养成健康饮食习惯。', f: 6, d: 1 },
  { w: 'proportion', ph: '/prəˈpɔːʃn/', pos: 'n.', cn: '比例，部分', en: 'a part in relation to the whole', se: 'A large proportion of the population lives in urban areas.', sc: '很大一部分人口居住在城市地区。', f: 5, d: 2 },
  { w: 'prospect', ph: '/ˈprɒspekt/', pos: 'n.', cn: '前景，展望', en: 'the possibility of future success', se: 'Job prospects for graduates in this field are excellent.', sc: '这个领域的毕业生就业前景非常好。', f: 4, d: 2 },
  { w: 'publish', ph: '/ˈpʌblɪʃ/', pos: 'v.', cn: '出版，发表', en: 'to produce and distribute', se: 'The research was published in a leading scientific journal.', sc: '该研究发表在一家领先的科学期刊上。', f: 5, d: 1 },
  { w: 'pursue', ph: '/pəˈsjuː/', pos: 'v.', cn: '追求，追赶', en: 'to follow or chase', se: 'She decided to pursue a career in medicine.', sc: '她决定从事医学事业。', f: 5, d: 1 },
  { w: 'radical', ph: '/ˈrædɪkl/', pos: 'adj.', cn: '根本的，激进的', en: 'relating to the root; extreme', se: 'The country needs radical reforms to boost its economy.', sc: '该国需要彻底的改革来提振经济。', f: 4, d: 2 },
  { w: 'range', ph: '/reɪndʒ/', pos: 'n./v.', cn: '范围，幅度', en: 'the extent of variation', se: 'The company offers a wide range of products.', sc: '该公司提供广泛的产品系列。', f: 5, d: 1 },
  { w: 'recognize', ph: '/ˈrekəɡnaɪz/', pos: 'v.', cn: '认出，承认', en: 'to identify or acknowledge', se: 'He is widely recognized as a leading expert in the field.', sc: '他被广泛认为是该领域的顶尖专家。', f: 6, d: 1 },
  { w: 'recommend', ph: '/ˌrekəˈmend/', pos: 'v.', cn: '推荐，建议', en: 'to suggest as good or suitable', se: 'Doctors recommend regular exercise for maintaining good health.', sc: '医生建议定期锻炼以保持健康。', f: 5, d: 1 },
  { w: 'reform', ph: '/rɪˈfɔːm/', pos: 'v./n.', cn: '改革，革新', en: 'to make changes for improvement', se: 'The government is pushing forward with educational reforms.', sc: '政府正在推进教育改革。', f: 5, d: 2 },
  { w: 'regulate', ph: '/ˈreɡjuleɪt/', pos: 'v.', cn: '监管，调节', en: 'to control by rules', se: 'The financial industry is heavily regulated by the government.', sc: '金融业受到政府的严格监管。', f: 4, d: 2 },
  { w: 'relevant', ph: '/ˈreləvənt/', pos: 'adj.', cn: '相关的，切题的', en: 'closely connected to the subject', se: 'The applicant\'s previous experience is highly relevant to this position.', sc: '申请人之前的经验与该职位高度相关。', f: 5, d: 1 },
  { w: 'reluctant', ph: '/rɪˈlʌktənt/', pos: 'adj.', cn: '不情愿的，勉强的', en: 'unwilling to do something', se: 'Many people are reluctant to change their daily habits.', sc: '许多人不愿意改变日常习惯。', f: 4, d: 2 },
  { w: 'rely', ph: '/rɪˈlaɪ/', pos: 'v.', cn: '依赖，信赖', en: 'to depend on', se: 'Many developing countries rely heavily on agriculture.', sc: '许多发展中国家严重依赖农业。', f: 5, d: 1 },
  { w: 'represent', ph: '/ˌreprɪˈzent/', pos: 'v.', cn: '代表，表示', en: 'to act or speak for', se: 'Each color on the map represents a different geological feature.', sc: '地图上的每种颜色代表不同的地质特征。', f: 5, d: 1 },
  { w: 'reputation', ph: '/ˌrepjuˈteɪʃn/', pos: 'n.', cn: '名声，声誉', en: 'the beliefs people hold about someone or something', se: 'The company has a reputation for high-quality products.', sc: '该公司以高质量产品闻名。', f: 4, d: 2 },
  { w: 'resource', ph: '/rɪˈsɔːs/', pos: 'n.', cn: '资源', en: 'a supply that can be used', se: 'Water is one of our most precious natural resources.', sc: '水是我们最宝贵的自然资源之一。', f: 6, d: 1 },
  { w: 'respond', ph: '/rɪˈspɒnd/', pos: 'v.', cn: '回应，反应', en: 'to react or reply', se: 'The government must respond quickly to public health emergencies.', sc: '政府必须对公共卫生紧急情况迅速做出反应。', f: 5, d: 1 },
  { w: 'restore', ph: '/rɪˈstɔː/', pos: 'v.', cn: '恢复，修复', en: 'to bring back to original state', se: 'Efforts are being made to restore the historic building.', sc: '正在努力修复这座历史建筑。', f: 4, d: 2 },
  { w: 'restrict', ph: '/rɪˈstrɪkt/', pos: 'v.', cn: '限制，约束', en: 'to put a limit on', se: 'The new law restricts the use of plastic bags.', sc: '新法律限制塑料袋的使用。', f: 4, d: 1 },
  { w: 'reveal', ph: '/rɪˈviːl/', pos: 'v.', cn: '揭示，显示', en: 'to make known', se: 'The investigation revealed serious flaws in the safety system.', sc: '调查揭示了安全系统中的严重缺陷。', f: 5, d: 1 },
  { w: 'revenue', ph: '/ˈrevənjuː/', pos: 'n.', cn: '收入，税收', en: 'income from business or taxes', se: 'The company\'s annual revenue exceeded $1 billion.', sc: '该公司年收入超过十亿美元。', f: 4, d: 2 },
  { w: 'reverse', ph: '/rɪˈvɜːs/', pos: 'v./adj./n.', cn: '逆转；相反的', en: 'to change to the opposite', se: 'The decline in the economy shows no sign of being reversed.', sc: '经济衰退没有逆转的迹象。', f: 4, d: 2 },
  { w: 'revolution', ph: '/ˌrevəˈluːʃn/', pos: 'n.', cn: '革命，变革', en: 'a fundamental change', se: 'The digital revolution has transformed every aspect of our lives.', sc: '数字革命改变了我们生活的方方面面。', f: 4, d: 2 },
  { w: 'risk', ph: '/rɪsk/', pos: 'n./v.', cn: '风险；冒险', en: 'the possibility of loss or harm', se: 'Regular exercise can significantly reduce the risk of heart disease.', sc: '定期锻炼可以显著降低患心脏病的风险。', f: 5, d: 1 },
  { w: 'rural', ph: '/ˈrʊərəl/', pos: 'adj.', cn: '农村的，乡村的', en: 'relating to the countryside', se: 'Access to healthcare is limited in many rural areas.', sc: '许多农村地区的医疗保健服务有限。', f: 4, d: 1 },
  { w: 'sacrifice', ph: '/ˈsækrɪfaɪs/', pos: 'v./n.', cn: '牺牲，奉献', en: 'to give up something for a greater good', se: 'Many parents sacrifice their own comfort for their children\'s education.', sc: '许多父母为了孩子的教育牺牲自己的舒适。', f: 4, d: 2 },
  { w: 'schedule', ph: '/ˈʃedjuːl/', pos: 'n./v.', cn: '时间表；安排', en: 'a plan of things to be done', se: 'The project is running ahead of schedule.', sc: '该项目正在提前进行。', f: 4, d: 1 },
  { w: 'scheme', ph: '/skiːm/', pos: 'n./v.', cn: '计划，方案', en: 'a systematic plan of action', se: 'The government introduced a new pension scheme for the elderly.', sc: '政府为老年人推出了一项新的养老金计划。', f: 4, d: 2 },
  { w: 'section', ph: '/ˈsekʃn/', pos: 'n.', cn: '部分，区域', en: 'a part of something', se: 'The library has a special section for rare books.', sc: '图书馆有一个特别的珍本书部。', f: 4, d: 1 },
  { w: 'security', ph: '/sɪˈkjʊərəti/', pos: 'n.', cn: '安全，保障', en: 'the state of being safe', se: 'Job security is a major concern for many workers.', sc: '工作保障是许多工人的主要关切。', f: 5, d: 1 },
  { w: 'shift', ph: '/ʃɪft/', pos: 'v./n.', cn: '转变，转移', en: 'to change position or direction', se: 'There has been a significant shift in public attitudes toward renewable energy.', sc: '公众对可再生能源的态度发生了重大转变。', f: 5, d: 1 },
  { w: 'significant', ph: '/sɪɡˈnɪfɪkənt/', pos: 'adj.', cn: '重要的，显著的', en: 'sufficiently large or important', se: 'The study found a significant correlation between exercise and mental health.', sc: '研究发现锻炼与心理健康之间存在显著关联。', f: 6, d: 1 },
  { w: 'similar', ph: '/ˈsɪmələ/', pos: 'adj.', cn: '相似的，类似的', en: 'resembling but not identical', se: 'The two theories share similar underlying assumptions.', sc: '这两种理论有相似的基本假设。', f: 5, d: 1 },
  { w: 'source', ph: '/sɔːs/', pos: 'n.', cn: '来源，出处', en: 'a place or thing from which something comes', se: 'The river is the main source of drinking water for the city.', sc: '这条河是该市饮用水的主要来源。', f: 5, d: 1 },
  { w: 'specific', ph: '/spəˈsɪfɪk/', pos: 'adj.', cn: '具体的，特定的', en: 'clearly defined or identified', se: 'The doctor gave specific instructions on how to take the medication.', sc: '医生对如何服药给出了具体的指示。', f: 5, d: 1 },
  { w: 'stable', ph: '/ˈsteɪbl/', pos: 'adj.', cn: '稳定的，稳固的', en: 'firmly fixed; not likely to change', se: 'The patient\'s condition remains stable after the surgery.', sc: '手术后病人的情况保持稳定。', f: 4, d: 1 },
  { w: 'status', ph: '/ˈsteɪtəs/', pos: 'n.', cn: '地位，状态', en: 'relative social or professional position', se: 'The status of women in society has improved greatly over the past century.', sc: '过去一个世纪里，妇女在社会中的地位有了很大提高。', f: 5, d: 1 },
  { w: 'stimulate', ph: '/ˈstɪmjuleɪt/', pos: 'v.', cn: '刺激，激励', en: 'to encourage or arouse', se: 'The government cut taxes to stimulate economic growth.', sc: '政府减税以刺激经济增长。', f: 4, d: 2 },
  { w: 'strategy', ph: '/ˈstrætədʒi/', pos: 'n.', cn: '策略，战略', en: 'a plan of action to achieve a goal', se: 'The company needs to develop a new marketing strategy.', sc: '公司需要制定新的营销策略。', f: 5, d: 1 },
  { w: 'strengthen', ph: '/ˈstreŋθn/', pos: 'v.', cn: '加强，增强', en: 'to make stronger', se: 'Regular exercise helps strengthen the immune system.', sc: '定期锻炼有助于增强免疫系统。', f: 4, d: 1 },
  { w: 'stress', ph: '/stres/', pos: 'n./v.', cn: '压力；强调', en: 'mental or emotional strain', se: 'Excessive stress can lead to serious health problems.', sc: '过度的压力可能导致严重的健康问题。', f: 4, d: 1 },
  { w: 'structure', ph: '/ˈstrʌktʃə/', pos: 'n./v.', cn: '结构；组织', en: 'the arrangement of parts', se: 'The company is undergoing a major restructuring.', sc: '该公司正在进行重大重组。', f: 5, d: 1 },
  { w: 'subsequent', ph: '/ˈsʌbsɪkwənt/', pos: 'adj.', cn: '随后的，后来的', en: 'coming after in time', se: 'Subsequent research confirmed the initial findings.', sc: '随后的研究证实了最初的发现。', f: 4, d: 2 },
  { w: 'substantial', ph: '/səbˈstænʃl/', pos: 'adj.', cn: '大量的，实质的', en: 'of considerable amount or size', se: 'The project requires a substantial amount of funding.', sc: '该项目需要大量的资金。', f: 4, d: 2 },
  { w: 'substitute', ph: '/ˈsʌbstɪtjuːt/', pos: 'v./n.', cn: '替代；替代品', en: 'a replacement', se: 'There is no substitute for hard work and dedication.', sc: '努力工作和奉献精神是无可替代的。', f: 4, d: 2 },
  { w: 'sufficient', ph: '/səˈfɪʃnt/', pos: 'adj.', cn: '足够的，充分的', en: 'enough to meet a need', se: 'The evidence is not sufficient to prove his guilt.', sc: '证据不足以证明他有罪。', f: 5, d: 1 },
  { w: 'superior', ph: '/suːˈpɪəriə/', pos: 'adj./n.', cn: '优越的；上级', en: 'higher in quality or rank', se: 'The product is superior in quality to its competitors.', sc: '该产品在质量上优于其竞争对手。', f: 4, d: 2 },
  { w: 'supply', ph: '/səˈplaɪ/', pos: 'n./v.', cn: '供应，供给', en: 'the amount of something available', se: 'The water supply in the region is threatened by drought.', sc: '该地区的供水受到干旱的威胁。', f: 5, d: 1 },
  { w: 'survey', ph: '/ˈsɜːveɪ/', pos: 'n./v.', cn: '调查，测量', en: 'a study of people\'s opinions', se: 'According to the survey, 70% of employees are satisfied with their jobs.', sc: '根据调查，70%的员工对自己的工作满意。', f: 5, d: 1 },
  { w: 'survive', ph: '/səˈvaɪv/', pos: 'v.', cn: '生存，存活', en: 'to remain alive', se: 'Only the strongest companies survive economic recessions.', sc: '只有最强大的公司才能在经济衰退中生存下来。', f: 5, d: 1 },
  { w: 'suspect', ph: '/səˈspekt/', pos: 'v./n.', cn: '怀疑；嫌疑人', en: 'to think something is true without proof', se: 'Police suspect the fire was started deliberately.', sc: '警方怀疑火灾是故意纵火。', f: 4, d: 1 },
  { w: 'suspend', ph: '/səˈspend/', pos: 'v.', cn: '暂停，悬挂', en: 'to temporarily stop or hang', se: 'The company suspended production due to safety concerns.', sc: '由于安全问题，该公司暂停了生产。', f: 4, d: 2 },
  { w: 'sustainable', ph: '/səˈsteɪnəbl/', pos: 'adj.', cn: '可持续的', en: 'able to be maintained over time', se: 'Sustainable development aims to meet present needs without compromising the future.', sc: '可持续发展旨在满足当前需求而不损害未来。', f: 5, d: 2 },
  { w: 'symbol', ph: '/ˈsɪmbl/', pos: 'n.', cn: '象征，符号', en: 'something that stands for something else', se: 'The dove is a symbol of peace.', sc: '鸽子是和平的象征。', f: 4, d: 1 },
  { w: 'temporary', ph: '/ˈtemprəri/', pos: 'adj.', cn: '暂时的，临时的', en: 'lasting for a limited time', se: 'Many graduates accept temporary jobs while looking for permanent positions.', sc: '许多毕业生在接受临时工作的同时寻找长期职位。', f: 4, d: 1 },
  { w: 'tend', ph: '/tend/', pos: 'v.', cn: '倾向于，往往会', en: 'to be likely to behave in a certain way', se: 'People tend to buy more when the economy is doing well.', sc: '经济好的时候人们往往会买更多东西。', f: 5, d: 1 },
  { w: 'tendency', ph: '/ˈtendənsi/', pos: 'n.', cn: '趋势，倾向', en: 'a likelihood to behave in a certain way', se: 'There is a growing tendency for people to work from home.', sc: '人们在家工作的趋势日益增长。', f: 4, d: 1 },
  { w: 'traditional', ph: '/trəˈdɪʃənl/', pos: 'adj.', cn: '传统的', en: 'long-established customs or beliefs', se: 'Traditional Chinese medicine has a history of thousands of years.', sc: '中医药有数千年的历史。', f: 5, d: 1 },
  { w: 'transfer', ph: '/trænsˈfɜː/', pos: 'v./n.', cn: '转移，调动', en: 'to move from one place to another', se: 'The patient was transferred to a specialized hospital.', sc: '病人被转到了专科医院。', f: 4, d: 1 },
  { w: 'transform', ph: '/trænsˈfɔːm/', pos: 'v.', cn: '转变，改造', en: 'to make a thorough change', se: 'The Internet has transformed the way we do business.', sc: '互联网改变了我们的经营方式。', f: 5, d: 2 },
  { w: 'trend', ph: '/trend/', pos: 'n.', cn: '趋势，潮流', en: 'a general direction of change', se: 'The trend toward urbanization continues in most developing countries.', sc: '大多数发展中国家的城市化趋势仍在继续。', f: 5, d: 1 },
  { w: 'unique', ph: '/juːˈniːk/', pos: 'adj.', cn: '独特的，唯一的', en: 'being the only one of its kind', se: 'Each species has its own unique characteristics.', sc: '每个物种都有其独特的特征。', f: 5, d: 1 },
  { w: 'urban', ph: '/ˈɜːbən/', pos: 'adj.', cn: '城市的，都市的', en: 'relating to a city', se: 'Urban populations are growing faster than rural ones.', sc: '城市人口比农村人口增长更快。', f: 4, d: 1 },
  { w: 'utilize', ph: '/ˈjuːtəlaɪz/', pos: 'v.', cn: '利用，使用', en: 'to make practical use of', se: 'The company aims to utilize advanced technology to improve efficiency.', sc: '该公司旨在利用先进技术提高效率。', f: 4, d: 2 },
  { w: 'valid', ph: '/ˈvælɪd/', pos: 'adj.', cn: '有效的，合理的', en: 'based on truth or reason', se: 'Your passport must be valid for at least six months beyond your travel dates.', sc: '你的护照有效期必须超过旅行日期至少六个月。', f: 4, d: 1 },
  { w: 'value', ph: '/ˈvæljuː/', pos: 'n./v.', cn: '价值；重视', en: 'the worth or importance of something', se: 'The cultural value of this heritage site is immeasurable.', sc: '这个文化遗产地的文化价值是不可估量的。', f: 5, d: 1 },
  { w: 'variety', ph: '/vəˈraɪəti/', pos: 'n.', cn: '多样性，种类', en: 'the quality of being different', se: 'The store offers a wide variety of organic products.', sc: '这家商店提供种类繁多的有机产品。', f: 5, d: 1 },
  { w: 'version', ph: '/ˈvɜːʃn/', pos: 'n.', cn: '版本，说法', en: 'a particular form of something', se: 'The latest version of the software includes many new features.', sc: '最新版本的软件包含许多新功能。', f: 4, d: 1 },
  { w: 'virtual', ph: '/ˈvɜːtʃuəl/', pos: 'adj.', cn: '虚拟的，实质上的', en: 'almost as described; simulated', se: 'Virtual reality technology is advancing rapidly.', sc: '虚拟现实技术正在快速发展。', f: 4, d: 1 },
  { w: 'visible', ph: '/ˈvɪzəbl/', pos: 'adj.', cn: '可见的，明显的', en: 'able to be seen', se: 'The effects of climate change are becoming increasingly visible.', sc: '气候变化的影响正变得越来越明显。', f: 4, d: 1 },
  { w: 'vision', ph: '/ˈvɪʒn/', pos: 'n.', cn: '愿景，视野', en: 'the ability to plan for the future', se: 'The company needs a clear vision for future growth.', sc: '公司需要有一个清晰的未来发展愿景。', f: 4, d: 1 },
  { w: 'vital', ph: '/ˈvaɪtl/', pos: 'adj.', cn: '至关重要的', en: 'absolutely necessary', se: 'Regular exercise is vital for maintaining good health.', sc: '定期锻炼对保持健康至关重要。', f: 4, d: 1 },
  { w: 'volume', ph: '/ˈvɒljuːm/', pos: 'n.', cn: '容量，音量，卷', en: 'the amount of space occupied', se: 'The volume of traffic on the roads continues to increase.', sc: '道路交通量持续增加。', f: 4, d: 1 },
  { w: 'voluntary', ph: '/ˈvɒləntəri/', pos: 'adj.', cn: '自愿的，志愿的', en: 'done by choice, not forced', se: 'Many people do voluntary work in their spare time.', sc: '许多人利用业余时间做志愿工作。', f: 4, d: 1 },
  { w: 'vulnerable', ph: '/ˈvʌlnərəbl/', pos: 'adj.', cn: '脆弱的，易受伤的', en: 'easily hurt or harmed', se: 'Children are the most vulnerable members of society.', sc: '儿童是社会中最脆弱的成员。', f: 4, d: 2 },
  { w: 'welfare', ph: '/ˈwelfeə/', pos: 'n.', cn: '福利，幸福', en: 'the health and happiness of people', se: 'The government is responsible for the welfare of its citizens.', sc: '政府负责其公民的福利。', f: 4, d: 2 },
  { w: 'widespread', ph: '/ˈwaɪdspred/', pos: 'adj.', cn: '广泛的，普遍的', en: 'spread over a large area', se: 'The use of smartphones has become widespread across all age groups.', sc: '智能手机的使用已经普及到所有年龄段。', f: 4, d: 1 },
  { w: 'witness', ph: '/ˈwɪtnəs/', pos: 'n./v.', cn: '目击者；目击', en: 'someone who sees an event', se: 'We are witnessing a historic moment in space exploration.', sc: '我们正在见证太空探索的历史性时刻。', f: 4, d: 1 },
  { w: 'worthwhile', ph: '/ˌwɜːθˈwaɪl/', pos: 'adj.', cn: '值得的', en: 'worth the time or effort', se: 'It is worthwhile to invest in early childhood education.', sc: '投资幼儿教育是值得的。', f: 4, d: 1 },
];

async function seed() {
  await initDb();
  const existing = get('SELECT COUNT(*) as c FROM words');
  if (existing.c > 0) {
    console.log(`词库已有 ${existing.c} 个词，跳过导入。`);
    return;
  }

  for (const w of words) {
    run('INSERT INTO words (word, phonetic, pos, definition_cn, definition_en, frequency, difficulty, sentence_en, sentence_cn) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
      [w.w, w.ph, w.pos, w.cn, w.en, w.f, w.d, w.se, w.sc]);
  }
  console.log(`✅ 成功导入 ${words.length} 个 CET-6 词汇！`);
}

seed().catch(err => { console.error('导入失败:', err); process.exit(1); });
